#!/bin/sh

# useful options (see zshoptions)

setopt autocd         # No need to write cd
setopt extendedglob   # Enables extended pattern matching 
setopt nomatch        #  
setopt menucomplete   # tab to cycle through possible completions

setopt interactive_comments # Enables comments within interactive shell
#zle_highlight('paste:none')

unsetopt BEEP

# Completions
autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
_comp_options+=(globdots) # Include hidden files

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors 
autoload -Uz colors && colors

# Useful functions
source "$ZDOTDIR/zsh-functions"

zsh_add_file "zsh-exports"
zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-aliases"

zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "romkatv/powerlevel10k"
